### PR TITLE
perf: use `neo-async` instead `async`

### PR DESCRIPTION
**Pull request by evilebottnawi**
### `Notable Changes`

- Increase performance

Reference: https://github.com/webpack/webpack/pull/6470

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@michael-ciniawsky can we merge and do release, it is really sppedup :smile:

**Comment by michael-ciniawsky** [comment]
Small benchmark or it didn't happen :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky Small benchmark :star:

**Pull request merged**
