### PR TITLE
Support for cacheContext override 

### PR DESCRIPTION
**Pull request by mistic**
This PR give the `cache-loader` users the ability to override the `cacheContext` (something close to what is being done into the dll plugin) in order to generate the cache asset paths relatively to another path. This will make it possible to save the cache and re-use it in the CI for example or even ship it for other usages.

This also close/replace https://github.com/webpack-contrib/cache-loader/pull/37 and close https://github.com/webpack-contrib/cache-loader/issues/36

\cc @evilebottnawi

### CODE REVIEW

**Comment by mistic** [comment]
@evilebottnawi some testes were for that specific option!

**Comment by mistic** [comment]
@evilebottnawi this PR here is dependent on https://github.com/webpack-contrib/cache-loader/pull/50 has I've used webpack 4 to run the tests

**Comment by evilebottnawi** [comment]
Need rebase and CI should be green

**Comment by mistic** [comment]
@evilebottnawi done

**Comment by mistic** [comment]
CI is green 🎉

**Pull request merged**
