### PR TITLE
Fix integration between prettier and eslint

### PR DESCRIPTION
**Pull request by mistic**
This fix the integration between prettier and eslint so we can have the prettier errors for source code included in the eslint report errors for a better debugging and development experience.

/CC @evilebottnawi

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Don't think this integration better because in future we will use remark for linting markdown and other linters, also eslint prettier it is new abstraction with own problems and bugs, better avoid this

**Comment by mistic** [comment]
@evilebottnawi then do you know any way to show debug information about the prettier failures only using prettier? Just fail on a file without letting know where is the line with the problem (and actually what is the problem) is not a very good experience

**Comment by evilebottnawi** [comment]
hm, i am using prettier as plugin for IDE, maybe we should improve this in prettier or use `--loglevel`, agree, let's solve this in future, not high priority right now

**Comment by mistic** [comment]
@evilebottnawi ok that makes sense, I will close this for now while you work on a fix in the prettier side. 
Meanwhile I've opened a PR to help minimize the problems

**Pull request closed without merging**
